version: 0.2

phases:
  install:  
    commands: 
      - npm install
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
  pre_build:
    commands:
      - CI=true npm test
  build:
    commands:
      - docker info
      - docker build -t astridnovicky/codebar-app:latest .
      - docker push astridnovicky/codebar-app
