version: 0.2

phases:
  install:  
    commands: 
      - npm install
      - apt-get update
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      - apt-get install -y docker-ce
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - CI=true npm test
  build:
    commands:
      - docker build -t astridnovicky/codebar-app:latest .
      - docker push astridnovicky/codebar-app
