version: 0.2

phases:
  install:  
    commands: 
      - npm install
  pre_build:
    commands:
      - CI=true npm test
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-2)
      - docker build -t codebar-app .
      - docker tag codebar-app:latest 762421145260.dkr.ecr.eu-west-2.amazonaws.com/codebar-app:latest
      - docker push 762421145260.dkr.ecr.eu-west-2.amazonaws.com/codebar-app:latest
