version: 0.2

phases:
  install:  
    commands: 
      - npm install
      - apt-get update
  pre_build:
    commands:
      - CI=true npm test
  build:
    commands:
      - docker build -t astridnovicky/codebar-app:latest .
      - docker push astridnovicky/codebar-app
